[package]
authors = ["Denis Daletski <daletskidenis@gmail.com>"]
edition = "2018"
name = "a-star"
version = "0.1.0"

[dependencies]
crossbeam-channel = "0.5.4"
eframe = "0.18.0"
image = "0.24.2"
rand = "0.8.5"
serde_json = "1.0"
