[package]
name = "a-star"
version = "0.1.0"
authors = ["Denis Daletski <daletskidenis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
image = "0.24.2"
rand = "0.8.5"