[package]
name = "percolations"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
union-find = { path = "../../union-find" }
ndarray = "0.15.3"
itertools = "0.10.1"
rand = "0.8.4"