[package]
name = "data_compression"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
bitvec = "1.0.1"
tap = "1.0.1"

[dev-dependencies]
proptest = "1.4.0"
rstest = "0.18.2"
criterion = "0.5.1"
