[package]
name = "common_algos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.4.0"
rand = "0.8.5"
rstest = "0.18.2"
spectral = "0.6.0"
