[package]
name = "rust-config-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"

[dependencies.syn]
version = "1.0.95"
features = ["full"]

[dependencies.rust-config-types]
path = "../types"
